### ISSUE TITLE
Refactoring with Jinja2 for templates

### ISSUE THREAD

**Issue by jackmaney** [juanpabloaj/pip-init#9]
Following up on #1, I took the liberty of using the [Jinja2](http://jinja.pocoo.org/docs/dev/) template engine, and I also added some basic questions around `packages` and `requirements`.

Since this...well...kind of stomps over your existing work, I figured I'd open an issue rather than create a pull request right off the bat. Let me know what you think!

https://github.com/jackmaney/pip-init/tree/jinja2

**Comment by jackmaney** [comment]
Note that I've removed the tests in this new branch (since they'll have to be rewritten anyway) and I haven't added any new documentation (save for a few comments in the code).

The code also isn't optimally DRY, but I'm leaving that alone for now, since it was not completely obvious at the time how to best abstract the prompts (although I think I can do that now). I've also done some manual testing.

Other things I'd like to tackle or see tackled:
- Automatically searching the distribution directory tree for non-python files and create a relatively simple way for the user to specify which of them--if any--s/he wants to include in the distribution (eg data files, etc).
- Sane handling of `MANIFEST.in` (if that's even possible :stuck_out_tongue:) if the user requests it.
- Grabbing more metadata from the `git` repository for the repo (if it exists).
- Using `tree` to create a basic visualization showing a diff of files that exist in the code base vs what is kept in a distribution (by doing a `python setup.py sdist`, opening up the resulting tarball, and peeking inside).
- Expanding the command line API: perhaps a `-i` flag to go into the full-blown interactive mode, choosing sane defaults if no arguments are provided, and perhaps being able to specify a configuration file (if things become unwieldy enough)?
-  Version hunting: do a basic search through the Python code files to see if any of them include a `__version__` variable. If more than one exists, try to pick intelligently, and when that's not possible, prompt the user to choose (if said option is configured).

**Comment by juanpabloaj** [comment]
@jackmaney thanks a lot for your effort, but I think that are many changes
-  jinja2 is necessary ? add jinja2 as dependency in a small package like pip-init?
- I decided use only a empty array in install_requires, `install_requires=[]`. (after read this post https://caremad.io/2013/07/setup-vs-requirement/)

but I like other things, like:
- get_input as a function, I was thinking about this and how make a test to raw_input (without mocking)
-  `fields` as dictionary, @davidyen1124  started with this idea https://github.com/davidyen1124/pip-init/commit/47e85f6ef3bafdaf897d77bf9afa3a627351e38b

My reasons are because I try to keep pip-init small and simple, and the generated ´setup.py´ file easy to understand for any new python developer.

I hope you undestand.

thanks again.

**Comment by jackmaney** [comment]
I understand your concerns, However:
- People coming to `pip-init` from Python web development will be largely right at home with templating engines, especially Jinja2, and more importantly
- A more robust template system will make the code easier to extend.

Thank you for starting this project.
